[package]
name = "solx-launchpad"
version = "0.1.0"
description = "SOLX mobile-first Solana launchpad program"
edition = "2021"
rust-version = "1.89.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "solx_launchpad"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []

[dependencies]
anchor-lang = "1.2.0"
anchor-spl = "1.2.0"
solana-security-txt = "1.1.3"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
